uppgift1VC/Controllers/CoordinatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Models;

namespace uppgift1VC.Controllers
{
    public class CoordinatorController : Controller
    {
        private IErrandRepository repository;
        public CoordinatorController(IErrandRepository repo)
        {
            repository = repo;
        }

        public ViewResult CrimeCoordinator(int id)
        {
            ViewBag.ID = id;
            return View(repository);
        }

        public ViewResult ReportCrime()
        {
            return View();
        }

        public ViewResult StartCoordinator()
        {
            return View(repository);
        }



    }
}

uppgift1VC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Infrastructure;
using uppgift1VC.Models;

namespace uppgift1VC.Controllers
{
    public class HomeController : Controller
    {

        private IErrandRepository repository;

        public HomeController(IErrandRepository repo)
        {
            repository = repo;
        }


        public ViewResult FAQ()
        {

            return View();
        }

        public ViewResult Contact()
        {
            return View();
        }

        public ViewResult Services()
        {
            return View();
        }

        public ViewResult Login()
        {
            return View();
        }

        public ViewResult Thanks()
        {
            Errand errand = HttpContext.Session.GetJson<Errand>("NewErrand");
            if (errand == null)
            {
                return View();
            }
            else
            {
                var newErrand = HttpContext.Session.GetJson<Errand>("NewErrand");
                
                repository.SaveErrand(errand);
                ViewBag.RefNum = errand.RefNumber;
                HttpContext.Session.Remove("NewErrand");
                return View(errand);
            }
        }

        public ViewResult Index()
        {
            var errand = HttpContext.Session.GetJson<Errand>("NewErrand");

            if (errand == null)
            {
                return View();
            }
            else
            {
                return View(errand);
            }
        }

        [HttpPost]
        public ViewResult Validate(Errand err)
        {
            HttpContext.Session.SetJson("NewErrand", err);
            return View(err);
        }

        public ViewResult SavedErrand()
        {
            HttpContext.Session.Remove("NewErrand");
            return View();
        }


    }
}

uppgift1VC/Controllers/InvestigatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Models;

namespace uppgift1VC.Controllers
{
    public class InvestigatorController : Controller
    {
        private IErrandRepository repository;

        public InvestigatorController(IErrandRepository repo)
        {
            repository = repo;
        }

        public ViewResult CrimeInvestigator(int id)
        {
            ViewBag.ID = id;
            return View(repository);
        }
        public ViewResult StartInvestigator()
        {
            return View(repository);
        }
    }
}

uppgift1VC/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Models;

namespace uppgift1VC.Controllers
{
    public class ManagerController : Controller
    {
        private IErrandRepository repository;

        public ManagerController(IErrandRepository repo)
        {
            repository = repo;
        }

        public ViewResult CrimeManager(int id)
        {
            ViewBag.ID = id;
            return View(repository);
        }

        public ViewResult StartManager()
        {
            return View(repository);
        }
    }
}

uppgift1VC/Views/Home/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<div id="content">
    <section id="mainColumn">
        <h2>Kontaktuppgifter</h2>
        <p><span class="label">Besöksadress:</span> Storgatan 42</p>
        <p><span class="label">Postadress:</span> Box 10, 909 00 Småstad</p>
        <p><span class="label">Mail:</span> miljoboven@smastad.nu</p>
        <p><span class="label">Telefon:</span> 432-500 10 00</p>
    </section><!-- End Left -->
</div>

uppgift1VC/Views/Home/FAQ.cshtml
@{
}

<div id="content">
    <section id="mainColumn">

        <h2>Frågor och svar om Miljöbrott</h2>
        <p class="info">Inga frågor är för dumma utom de som verkligen är det</p>

        <p>
            <span class="label">Varför måste jag fylla i mitt namn och telefonnummer?</span><br />
            Eftersom vi vill kunna kontakta dig för kompletterande information så måste vi veta vem du är.
        </p>

        <p>
            <span class="label">Vilka typer av miljöbrott kan man anmäla?</span><br />
            Allt möjligt, anmäl även om du är osäker. Vi utreder allt och tar beslut om det är något som ska vidare.
        </p>

        <p>
            <span class="label">Jag har tagit bilder och vill skicka med, hur gör jag?</span><br />
            Skicka in dem med vanlig post eller via email och berätta till vilken anmälan de hör ihop med
            (ange numret du fick när du gjorde anmälan).
        </p>

        <p>
            <span class="label">Vad gör jag med de dumma frågor jag har?</span><br />
            Du håller dem för dig själv, vi har inte tid att hantera sådana
        </p>

        <p>Fick du inte svar på din fråga? <a asp-controller="Home" asp-action="Contact">Maila eller ring till oss</a>.</p>
    </section><!-- End Left -->
</div>

uppgift1VC/Views/Home/Index.cshtml
@{
    @model Errand

}


<div id="content">
    <section id="mainColumn">
        <h2>Välkommen att fylla i din anmälan av miljöbrott</h2>
        <p class="info">I Småstad är inga brott för små för att anmälas</p>

        <p>Fyll i formuläret nedan, alla rutor markerade med stjärna (*) måste fyllas i.</p>

        <form method="post" asp-controller="Home" asp-action="Validate">
            <div asp-validation-summary="All"></div>

            <p>
                <input type="hidden" name="isSubmitted" value="true" />
            </p>
            <p>
                <label asp-for="Place" class="label">Var har brottet skett någonstans?</label><br />
                <input asp-for="Place" /> *
            </p>
            <p>
                <label asp-for="TypeOfCrime" class="label"></label><br />
                <input asp-for="TypeOfCrime" /> *
            </p>
            <p>
                <label asp-for="DateOfObservation" class="label">När skedde brottet?</label><br />
                <input asp-for="DateOfObservation" /> *
            </p>
            <p>
                <label asp-for="InformerName" class="label"></label><br />
                <input asp-for="InformerName" /> *
            </p>
            <p>
                <label asp-for="InformerPhone" class="label"></label><br />
                <input asp-for="InformerPhone" /> *
            </p>
            <p>
                <label asp-for="Observation" class="label">Beskriv din observation<br /> (ex. namn på misstänkt person):</label><br />
                <textarea asp-for="Observation" rows="5" cols="16"></textarea>
            </p>
            <p>
                <input class="button" type="submit" value="Skicka in" />
            </p>
        </form>
    </section><!-- End Left -->
</div>

uppgift1VC/Views/Home/Login.cshtml
@{

}
<section id="mainColumn">
    <h2>Inloggning för Småstads personal</h2>
    <p class="info">En säker tjänst från Småstads IT-avdelning</p>

    <form method="post" action="coordinator/startCoordinator.html">
        <p>
            <input type="hidden" name="isSubmitted" value="true" />
        </p>
        <p>
            <span class="label">Användarnamn:</span><br />
            <input type="text" name="user" />
        </p>
        <p>
            <span class="label">Lösenord:</span><br />
            <input type="password" name="password" />
        </p>
        <p>
            <input class="button" type="submit" value="Inloggning av samordnare" asp-controller="Coordinator" asp-action="StartCoordinator" />
            <br />
            <!--Dessa länkar ska sedan tas bort då det är meningen att vid kontrollen av inloggningsuppgifter så hämtas rätt sida-->
            <a class="button" asp-controller="Manager" asp-action="StartManager">Inloggning av chefer</a><br />
            <a class="button" asp-controller="Investigator" asp-action="StartInvestigator">Inloggning av handläggare</a>
        </p>
    </form>
</section>

uppgift1VC/Views/Home/Services.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


    <section id="mainColumn">
        <h2>Avdelningar och Tjänster</h2>
        <p class="info">Vi bryr oss om dig</p>

        <p>Folkhälsa - Hälso- och Sjukvård, Tandvård - Socialtjänst och omsorg - Trygghet och säkerhet</p>
        <p>Bygga och bo - Gator och parker - Kollektivtrafiken - Miljö- och hälsoskydd - Sophantering och återvinning</p>
        <p>Barn och utbildning - Kultur och fritid</p>
        <p>Företagsservice</p>
    </section><!-- End Left -->

uppgift1VC/Views/Home/Thanks.cshtml
@{
    @model Errand
}

<div id="content">
    <h2>Tack för din anmälan</h2>
    <p class="info">Du är inloggad som samordnare</p>

    <p>
        Anmälan har nu skickats in till kommunen och kommer att utredas. <br />
        Vill du komplettera din anmälan kontakta oss via mail eller telefon. <br />
        Ange då nummer: @ViewBag.RefNum
    </p>

    <p><a class="button" asp-action="Index" asp-controller="Home">Avsluta rapporteringen</a></p>

</div><!-- End Content -->

uppgift1VC/Views/Home/Validate.cshtml
@model Errand


<div id="content">
    <h2>Din anmälan av miljöbrott</h2>
    <p class="info">Du är inloggad som samordnare</p>

    <p class="label">
        Vänligen läs igenom din anmälan och se att allt är okej.<br />
        Om något är fel, gå tillbaka och ändra. Annars välj Bekräfta.
    </p>
    <p>
        <span class="label">Var har brottet skett någonstans?</span><br />@Model.Place
       
    </p>
    <p>
        <span class="label">Vilken typ av brott?</span><br />@Model.TypeOfCrime
       
    </p>
    <p>
        <span class="label">När skedde brottet?</span><br />@Model.DateOfObservation
        
    </p>
    <p>
        <span class="label">Ditt namn (för- och efternamn):</span><br />@Model.InformerName
        
    </p>
    <p>
        <span class="label">Din telefon:</span><br />@Model.InformerPhone
        
    </p>    
    <p>
        <span class="label">Mer information:</span><br />@Model.Observation
        <br />
    </p>
    <p>
        <a class="button" asp-action="Index" asp-controller="Home" id="link">Tillbaka</a>
        <a class="button" asp-action="Thanks" asp-controller="Home">Bekräfta</a>
    </p>


</div><!-- End Content -->