uppgift1VC/Components/ErrandListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Models;

namespace uppgift1VC.Components
{
    public class ErrandListViewComponent : ViewComponent
    {
        private IErrandRepository errandRepository;
        public ErrandListViewComponent(IErrandRepository repo)
        {
            errandRepository = repo;

        }
        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var errandInfo = await errandRepository.GetErrandInfo(id);
            return View(errandInfo);
        }

    }
}

uppgift1VC/Controllers/InvestigatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using uppgift1VC.Models;

namespace uppgift1VC.Controllers
{
    public class InvestigatorController : Controller
    {
        private IErrandRepository repository;

        public InvestigatorController(IErrandRepository repo)
        {
            repository = repo;
        }

        public ViewResult CrimeInvestigator(int id)
        {
            ViewBag.ID = id;
            return View(repository);
        }
        public ViewResult StartInvestigator()
        {
            return View(repository);
        }
    }
}

uppgift1VC/Views/Investigator/CrimeInvestigator.cshtml
@{
    Layout = "_LayoutInvestigator";
}
@model IErrandRepository;

<div id="content">
    <h2>Detaljer för ärendet</h2>
    <p class="info">Du är inloggad som handläggare</p>


    <!--Nedan ser man en lista på ärenden-->
    @*viewComponent*@

    @await Component.InvokeAsync("ErrandList",ViewBag.ID)

    <section id="bottomColumn">
        <h3>Redigera ärende</h3>
        <p class="label">Händelser:</p>
        <textarea name="events" rows="5" cols="60"></textarea>

        <p class="label">Mer information:</p>
        <textarea name="information" rows="5" cols="60"></textarea>

        <p class="label">Prover:</p>
        <input type="file" name="loadSample" />

        <p class="label">Ladda upp bilder:</p>
        <input type="file" name="loadImage" />

        <p class="label">Ändring av status:</p>
        <select name="status">
            <option selected="selected">Välj</option>
            @foreach (ErrandStatus errand in Model.ErrandStatuses)
            {
                <option>@errand.StatusName</option>
            }
        </select>

        <p>
            <input class="button" type="submit" value="Spara ändringarna" />
        </p>
    </section>


</div><!-- End Content -->

uppgift1VC/Views/Investigator/StartInvestigator.cshtml
@{

    Layout = "_LayoutInvestigator";

}

@model IErrandRepository;

<div id="content">
    <h2>Ärenden</h2>
    <p class="info">Du är inloggad som handläggare</p>


    <table id="managerForm">
        <tr>
            <td class="label">Välj status:</td>
            <td>&nbsp;</td>
            <td class="label">Ärendenummer:</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <select name="status">
                    <option selected="selected">Välj alla</option>
                    @foreach (ErrandStatus errand in Model.ErrandStatuses)
                    {
                        <option>@errand.StatusName</option>
                    }
                </select>
            </td>
            <td><input class="button" type="submit" value="Hämta lista" /></td>
            <td><input name="casenumber" /></td>
            <td><input class="button" type="submit" value="Sök" /></td>
        </tr>
    </table>

    <!--Nedan ser man en lista på ärenden-->
    <table>
        <tr>
            <th>Ärende anmält</th>
            <th>Ärendenummer</th>
            <th>Miljöbrott</th>
            <th>Status</th>
            <th>Avdelning</th>
            <th>Handläggare</th>
        </tr>

        @foreach (Errand errand in Model.Errands)
        {
            <tr>
                <td>@errand.DateOfObservation.ToShortDateString()</td>
                <td><a asp-controller="Investigator" asp-action="CrimeInvestigator" asp-route-id="@errand.ErrandID">@errand.RefNumber</a></td>
                <td>@errand.TypeOfCrime</td>
                <td>@errand.StatusId</td>
                <td>@errand.DepartmentId</td>
                <td>@errand.EmployeeId</td>
            </tr>
        }


    </table>


</div><!-- End Content -->